name: 🔄 Sync Files

description: Sincroniza arquivos via rsync

# Inputs
inputs:
  ssh_key:
    required: true
  remote_host:
    required: true
  remote_user:
    required: true
  source:
    required: true
  destination:
    required: true
  port:
    required: false
    type: number
    default: 22

runs:
  using: "composite"
  steps:
    - name: 📂 Sync Files
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ inputs.ssh_key }}
        REMOTE_HOST: ${{ inputs.remote_host }}
        REMOTE_USER: ${{ inputs.remote_user }}
        REMOTE_PORT: ${{ inputs.port }}
        SOURCE: "${{ inputs.source }}/"
        TARGET: "${{ inputs.destination }}/"
        EXCLUDE: "/.git/, /README.md, /readme.md, /.gitignore"